import '../app/global.css';
import { Poppins } from 'next/font/google'
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

const poppins = Poppins({
    weight: '400',
    subsets: ['latin'],
    variable: '--font-poppins-mono',
    display: 'swap',
})
// Assuming global.css is one folder up from pages

function MyApp({ Component, pageProps }) {
    return (
        <div className={`${poppins.variable}`}>
            <Component {...pageProps} />
        </div>
    )
}

export default MyApp;